### ISSUE TITLE
Add link to Onename source repo

### ISSUE THREAD

**Issue by plato-cambrian** [onenameio/onename-blog#1]
I can't find a Onename repo, I would like to file issues "how do I generate a proof" and "what do I need to do to create and secure my namecoin address"

Is the code base open source? This project looks like it might solve the issue of decentralizing proof of identity, but not if Onename.com is the only provider

**Comment by john-light** [comment]
@plato-cambrian just saw your comment here - all of Onename's backend code has been contributed to the open source Blockstack community GitHub: http://github.com/blockstack 

I invite you to join us at http://chat.blockstack.org.

**Comment by plato-cambrian** [comment]
Thanks @john-light for the reply and open source code!
